name: Build Flutter Apps (Android & Windows)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

     - name: Install Dependencies
        run: |
          cd flutter_app
          flutter pub get

      - name: Build APK
        run: |
          cd flutter_app
          flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Mobile-Android-APK
          path: flutter_app/build/app/outputs/flutter-apk/app-release.apk

  build-windows:
    name: Build Windows EXE
    runs-on: windows-latest
    steps:
      - uses: actions/chekout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Install Dependencies
        run: |
          cd flutter_app
          flutter pub get

      - name: Build Windows Executable
        run: |
          cd flutter_app
          flutter build windows

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
       with:
          name: Desktop-Windows-EXE
          path: flutter_app/build/windows/x64/runner/Release/
