name: Build Apps

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter create --platforms=android .
      - run: flutter pub get
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: build/app/outpus/flutter-apk/app-release.apk

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter create --platforms=windows .
      - run: flutter config --enable-windows-desktop
      - run: flutter pub get
      - run: flutter build windows
      - uses: actions/upload-artifact@v4
        with:
          name: Windows-EXE
          path: build/windows/x64/runner/Release/
